"""add device coordinates

Revision ID: 2d9148ce6dd4
Revises: d9344d910ec6
Create Date: 2026-10-01 17:18:30.135012
"""
from alembic import op
import sqlalchemy as sa


revision = '2d9148ce6dd4'
down_revision = 'd9344d910ec6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('devices', sa.Column('longitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('devices', 'longitude')
    op.drop_column('devices', 'latitude')
    # ### end Alembic commands ###
