"""add geofence tracking interval

Revision ID: 4b56c313564b
Revises: 2d9148ce6dd4
Create Date: 2026-10-01 17:46:23.840121
"""
from alembic import op
import sqlalchemy as sa


revision = '4b56c313564b'
down_revision = '2d9148ce6dd4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('geofences', sa.Column('tracking_interval_seconds', sa.Integer(), server_default='60', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('geofences', 'tracking_interval_seconds')
    # ### end Alembic commands ###
