"""add advanced geofence API support

Revision ID: d6e3154d502d
Revises: 4b56c313564b
Create Date: 2026-10-01 18:14:38.970250
"""
from alembic import op
import sqlalchemy as sa


revision = 'd6e3154d502d'
down_revision = '4b56c313564b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
