"""initial geofencing schema

Revision ID: d9344d910ec6
Revises: 
Create Date: 2026-10-01 15:59:40.989540
"""
from alembic import op
import sqlalchemy as sa


revision = 'd9344d910ec6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('entity_type', sa.String(length=80), nullable=False),
    sa.Column('entity_id', sa.String(length=80), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('geofences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('boundary_type', sa.Enum('circle', 'polygon', name='boundarytype'), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('center_latitude', sa.Float(), nullable=True),
    sa.Column('center_longitude', sa.Float(), nullable=True),
    sa.Column('radius_meters', sa.Float(), nullable=True),
    sa.Column('accuracy_buffer_meters', sa.Float(), nullable=False),
    sa.Column('event_rules', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=120), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_devices_external_id'), 'devices', ['external_id'], unique=True)
    op.create_table('geofence_points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('geofence_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['geofence_id'], ['geofences.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_geofence_points_geofence_id'), 'geofence_points', ['geofence_id'], unique=False)
    op.create_table('location_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.Column('received_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_location_events_device_id'), 'location_events', ['device_id'], unique=False)
    op.create_index(op.f('ix_location_events_recorded_at'), 'location_events', ['recorded_at'], unique=False)
    op.create_table('geofence_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('geofence_id', sa.Integer(), nullable=False),
    sa.Column('location_event_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.Enum('enter', 'exit', 'inside', 'outside', name='eventtype'), nullable=False),
    sa.Column('previous_state', sa.Enum('inside', 'outside', name='fencestate'), nullable=True),
    sa.Column('current_state', sa.Enum('inside', 'outside', name='fencestate'), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['geofence_id'], ['geofences.id'], ),
    sa.ForeignKeyConstraint(['location_event_id'], ['location_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_geofence_events_device_id'), 'geofence_events', ['device_id'], unique=False)
    op.create_index(op.f('ix_geofence_events_event_type'), 'geofence_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_geofence_events_geofence_id'), 'geofence_events', ['geofence_id'], unique=False)
    op.create_index(op.f('ix_geofence_events_location_event_id'), 'geofence_events', ['location_event_id'], unique=False)
    op.create_index(op.f('ix_geofence_events_occurred_at'), 'geofence_events', ['occurred_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_geofence_events_occurred_at'), table_name='geofence_events')
    op.drop_index(op.f('ix_geofence_events_location_event_id'), table_name='geofence_events')
    op.drop_index(op.f('ix_geofence_events_geofence_id'), table_name='geofence_events')
    op.drop_index(op.f('ix_geofence_events_event_type'), table_name='geofence_events')
    op.drop_index(op.f('ix_geofence_events_device_id'), table_name='geofence_events')
    op.drop_table('geofence_events')
    op.drop_index(op.f('ix_location_events_recorded_at'), table_name='location_events')
    op.drop_index(op.f('ix_location_events_device_id'), table_name='location_events')
    op.drop_table('location_events')
    op.drop_index(op.f('ix_geofence_points_geofence_id'), table_name='geofence_points')
    op.drop_table('geofence_points')
    op.drop_index(op.f('ix_devices_external_id'), table_name='devices')
    op.drop_table('devices')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('geofences')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
