import { useEffect, useState } from "react";
import { CheckCircleRounded, DeviceHubRounded, ExploreRounded, LocationOnRounded, NotificationsActiveRounded, TrendingUpRounded } from "@mui/icons-material";
import { Alert, Avatar, Box, Chip, CircularProgress, Grid2 as Grid, Paper, Stack, Table, TableBody, TableCell, TableHead, TableRow, Typography } from "@mui/material";
import { getDevices, getEvents, getGeofences } from "../api";
import { Device, EventRecord, Geofence } from "../types";

const activityStyle = (type: string) => type === "enter" ? { bg: "#dcfce7", text: "#15803d" } : type === "exit" ? { bg: "#fee2e2", text: "#dc2626" } : type === "inside" ? { bg: "#dbeafe", text: "#1d4ed8" } : { bg: "#fef3c7", text: "#b45309" };
export function DashboardPage() {
  const [fences, setFences] = useState<Geofence[]>([]), [events, setEvents] = useState<EventRecord[]>([]), [devices, setDevices] = useState<Device[]>([]), [error, setError] = useState("");
  useEffect(() => { Promise.all([getGeofences(), getEvents(), getDevices()]).then(([fenceData, eventData, deviceData]) => { setFences(fenceData); setEvents(eventData); setDevices(deviceData); }).catch(() => setError("Could not reach the API. Start FastAPI on port 8000.")); }, []);
  if (!fences.length && !error && !devices.length) return <Box sx={{ display: "grid", placeItems: "center", minHeight: 300 }}><CircularProgress /></Box>;
  const metrics = [
    { label: "Geofences", value: fences.length, caption: `${fences.filter(fence => fence.enabled).length} active boundaries`, icon: <LocationOnRounded />, gradient: "linear-gradient(135deg, #2563eb, #4f46e5)", shadow: "rgba(37, 99, 235, .25)" },
    { label: "Inside zones", value: events.filter(event => event.current_state === "inside").length, caption: "Latest location events", icon: <CheckCircleRounded />, gradient: "linear-gradient(135deg, #059669, #14b8a6)", shadow: "rgba(5, 150, 105, .25)" },
    { label: "Outside zones", value: events.filter(event => event.current_state === "outside").length, caption: "Latest location events", icon: <ExploreRounded />, gradient: "linear-gradient(135deg, #f59e0b, #f97316)", shadow: "rgba(245, 158, 11, .25)" },
    { label: "Active devices", value: devices.filter(device => device.enabled).length, caption: `of ${devices.length} registered`, icon: <DeviceHubRounded />, gradient: "linear-gradient(135deg, #8b5cf6, #d946ef)", shadow: "rgba(139, 92, 246, .25)" }
  ];
  return <Box><Stack direction={{ xs: "column", md: "row" }} justifyContent="space-between" alignItems={{ md: "center" }} mb={3} gap={2}><Box><Typography variant="h4">Dashboard</Typography><Typography color="text.secondary">Real-time geofence intelligence and device activity.</Typography></Box></Stack>{error && <Alert severity="warning" sx={{ mb: 2 }}>{error}</Alert>}
    <Grid container spacing={2.25} mb={4}>{metrics.map(metric => <Grid key={metric.label} size={{ xs: 12, sm: 6, lg: 3 }}><Paper sx={{ p: 2.25, color: "white", overflow: "hidden", position: "relative", minHeight: 158, background: metric.gradient, border: 0, boxShadow: `0 14px 28px ${metric.shadow}` }}><Box sx={{ position: "absolute", right: -13, top: -19, opacity: .15, transform: "rotate(-12deg)", "& svg": { fontSize: 145 } }}>{metric.icon}</Box><Stack direction="row" justifyContent="space-between" alignItems="center"><Typography fontWeight={700} sx={{ opacity: .88 }}>{metric.label}</Typography><Avatar sx={{ bgcolor: "rgba(255,255,255,.18)", color: "white" }}>{metric.icon}</Avatar></Stack><Typography variant="h2" fontWeight={800} sx={{ mt: 1.5, letterSpacing: "-0.05em" }}>{metric.value}</Typography><Typography variant="body2" sx={{ opacity: .86 }}>{metric.caption}</Typography></Paper></Grid>)}</Grid>
    <Paper sx={{ overflow: "hidden" }}><Stack direction={{ xs: "column", sm: "row" }} justifyContent="space-between" alignItems={{ sm: "center" }} sx={{ p: 2.5, background: "linear-gradient(90deg, #f8fbff, #f1f7ff)", borderBottom: "1px solid #e5edf7" }}><Box><Typography variant="h6">Recent device activity</Typography><Typography variant="body2" color="text.secondary">The most recent geofence actions across your fleet.</Typography></Box><Stack direction="row" alignItems="center" spacing={.75}><TrendingUpRounded color="success" fontSize="small" /><Typography variant="body2" color="success.main" fontWeight={750}>Live</Typography></Stack></Stack><Table><TableHead><TableRow><TableCell>Date & time</TableCell><TableCell>Device</TableCell><TableCell>Geofence</TableCell><TableCell>Action</TableCell></TableRow></TableHead><TableBody>{events.slice(0, 10).map(event => { const style = activityStyle(event.event_type); return <TableRow key={event.id}><TableCell><Typography fontWeight={650}>{new Date(event.occurred_at).toLocaleString()}</Typography></TableCell><TableCell><Typography fontWeight={700}>{event.device_name}</Typography></TableCell><TableCell><Typography fontWeight={650}>{event.geofence_name}</Typography></TableCell><TableCell><Chip label={event.event_type.toUpperCase()} size="small" sx={{ bgcolor: style.bg, color: style.text, fontWeight: 850, minWidth: 72 }} /></TableCell></TableRow>; })}{events.length === 0 && <TableRow><TableCell colSpan={4} align="center" sx={{ py: 7 }}><Typography fontWeight={700}>No device activity yet.</Typography><Typography variant="body2" color="text.secondary">Location updates will appear here when devices are tracked.</Typography></TableCell></TableRow>}</TableBody></Table></Paper>
  </Box>;
}
