import { useEffect, useMemo, useState } from "react";
import { AddRounded, DeleteOutlineRounded, EditOutlined, FmdGoodOutlined, MoreHorizRounded, SearchRounded, TuneRounded } from "@mui/icons-material";
import { Avatar, Box, Button, Chip, CircularProgress, IconButton, InputAdornment, MenuItem, Paper, Stack, Table, TableBody, TableCell, TableContainer, TableHead, TableRow, TextField, Tooltip, Typography } from "@mui/material";
import { Link } from "react-router-dom";
import { deleteGeofence, getGeofences, setGeofenceStatus } from "../api";
import { PageHero } from "../components/PageHero";
import { Geofence } from "../types";

const typeColor = (type: Geofence["boundary_type"]) => type === "circle" ? "#246bfd" : "#8b5cf6";
export function GeofencesPage() {
  const [items, setItems] = useState<Geofence[]>([]), [query, setQuery] = useState(""), [filter, setFilter] = useState("all"), [loading, setLoading] = useState(true);
  const load = () => { setLoading(true); return getGeofences().then(setItems).finally(() => setLoading(false)); };
  useEffect(() => { load(); }, []);
  const visible = useMemo(() => items.filter(fence => (filter === "all" || (filter === "active" ? fence.enabled : !fence.enabled)) && fence.name.toLowerCase().includes(query.toLowerCase())), [items, query, filter]);
  const remove = (fence: Geofence) => { if (window.confirm(`Delete ${fence.name}?`)) deleteGeofence(fence.id).then(load); };
  const metrics = [{ label: "Total geofences", value: items.length, tint: "#246bfd" }, { label: "Active boundaries", value: items.filter(f => f.enabled).length, tint: "#14b8a6" }, { label: "Circular zones", value: items.filter(f => f.boundary_type === "circle").length, tint: "#8b5cf6" }];
  return <Box>
    <PageHero title="Geofences" subtitle="Manage protected zones, event rules, and boundary coverage." icon={<FmdGoodOutlined />} gradient="linear-gradient(135deg, #1d4ed8, #2563eb)" action={<Stack direction="row" spacing={1}><Chip label={`${items.length} GEOFENCES`} sx={{ bgcolor: "rgba(255,255,255,.18)", color: "white", fontWeight: 800 }} /><Button component={Link} to="/geofences/new" variant="contained" startIcon={<AddRounded />} sx={{ bgcolor: "white", color: "primary.main", "&:hover": { bgcolor: "#eef5ff" } }}>Create geofence</Button></Stack>} />
    <Stack direction={{ xs: "column", md: "row" }} spacing={2} mb={3}>{metrics.map(metric => <Paper key={metric.label} sx={{ flex: 1, p: 2, display: "flex", alignItems: "center", gap: 1.5 }}><Avatar sx={{ bgcolor: `${metric.tint}18`, color: metric.tint, fontWeight: 800 }}>{metric.value}</Avatar><Box><Typography variant="h5" lineHeight={1.1}>{metric.value}</Typography><Typography variant="body2" color="text.secondary">{metric.label}</Typography></Box></Paper>)}</Stack>
    <Paper sx={{ overflow: "hidden" }}><Stack direction={{ xs: "column", md: "row" }} spacing={1.5} p={2.25} alignItems={{ md: "center" }} justifyContent="space-between" borderBottom="1px solid #e5edf7"><TextField size="small" placeholder="Search geofences" value={query} onChange={event => setQuery(event.target.value)} sx={{ minWidth: { md: 300 } }} InputProps={{ startAdornment: <InputAdornment position="start"><SearchRounded color="action" fontSize="small" /></InputAdornment> }} /><Stack direction="row" spacing={1}><TextField select size="small" value={filter} onChange={event => setFilter(event.target.value)} sx={{ minWidth: 140 }} InputProps={{ startAdornment: <InputAdornment position="start"><TuneRounded fontSize="small" /></InputAdornment> }}><MenuItem value="all">All statuses</MenuItem><MenuItem value="active">Active</MenuItem><MenuItem value="inactive">Inactive</MenuItem></TextField><Tooltip title="More filters"><IconButton><MoreHorizRounded /></IconButton></Tooltip></Stack></Stack>
      {loading ? <Box p={6} textAlign="center"><CircularProgress /></Box> : <TableContainer><Table><TableHead><TableRow><TableCell>Geofence</TableCell><TableCell>Boundary</TableCell><TableCell>Event rules</TableCell><TableCell>Tracking</TableCell><TableCell>Status</TableCell><TableCell align="right">Actions</TableCell></TableRow></TableHead><TableBody>{visible.map(fence => <TableRow key={fence.id}><TableCell><Stack direction="row" alignItems="center" spacing={1.25}><Box><Typography fontWeight={750}>{fence.name}</Typography><Typography variant="caption" color="text.secondary">{fence.boundary_type === "circle" ? "Radius boundary" : "Polygon boundary"}</Typography></Box></Stack></TableCell><TableCell><Chip size="small" label={fence.boundary_type === "circle" ? `${fence.radius_meters} m radius` : `${fence.points.length} boundary points`} sx={{ bgcolor: `${typeColor(fence.boundary_type)}14`, color: typeColor(fence.boundary_type) }} /></TableCell><TableCell><Stack direction="row" spacing={.5} flexWrap="wrap" useFlexGap>{Object.entries(fence.event_rules).filter(([, enabled]) => enabled).map(([rule]) => <Chip key={rule} label={rule.toUpperCase()} size="small" variant="outlined" />)}</Stack></TableCell><TableCell><Typography fontWeight={650}>{fence.tracking_interval_seconds}s</Typography><Typography variant="caption" color="text.secondary"></Typography></TableCell><TableCell><Tooltip title={`Click to mark ${fence.enabled ? "inactive" : "active"}`}><Chip clickable onClick={() => setGeofenceStatus(fence.id, !fence.enabled).then(load)} label={fence.enabled ? "ACTIVE" : "INACTIVE"} size="small" sx={fence.enabled ? { bgcolor: "#dcfce7", color: "#15803d", border: "1px solid #86efac", fontWeight: 800 } : { bgcolor: "#fee2e2", color: "#dc2626", border: "1px solid #fca5a5", fontWeight: 800 }} /></Tooltip></TableCell><TableCell align="right"><Tooltip title="Edit geofence"><IconButton component={Link} to={`/geofences/${fence.id}/edit`} sx={{ color: "primary.main", bgcolor: "#edf4ff", mr: .75 }}><EditOutlined fontSize="small" /></IconButton></Tooltip><Tooltip title="Delete geofence"><IconButton color="error" onClick={() => remove(fence)} sx={{ bgcolor: "#fff1f2" }}><DeleteOutlineRounded fontSize="small" /></IconButton></Tooltip></TableCell></TableRow>)}{visible.length === 0 && <TableRow><TableCell colSpan={6} align="center" sx={{ py: 7 }}><FmdGoodOutlined color="disabled" sx={{ fontSize: 42, mb: 1 }} /><Typography fontWeight={700}>No geofences found</Typography><Typography variant="body2" color="text.secondary">Try changing the filter or create a new protected zone.</Typography></TableCell></TableRow>}</TableBody></Table></TableContainer>}</Paper>
  </Box>;
}
