import { DashboardOutlined, DevicesOutlined, HistoryOutlined, LocationOnOutlined, MapOutlined, Menu as MenuIcon, NotificationsNoneOutlined, PolicyOutlined } from "@mui/icons-material";
import { AppBar, Avatar, Box, CssBaseline, Divider, Drawer, IconButton, List, ListItemButton, ListItemIcon, ListItemText, Stack, Toolbar, Typography } from "@mui/material";
import { Link, Route, Routes, useLocation } from "react-router-dom";
import { DashboardPage } from "./pages/DashboardPage";
import { AuditLogsPage } from "./pages/AuditLogsPage";
import { DevicesPage } from "./pages/DevicesPage";
import { EventsPage } from "./pages/EventsPage";
import { GeofenceFormPage } from "./pages/GeofenceFormPage";
import { GeofencesPage } from "./pages/GeofencesPage";
import { LiveMapPage } from "./pages/LiveMapPage";

const width = 264;
const menu = [{ label: "Dashboard", to: "/", icon: <DashboardOutlined /> }, { label: "Live map", to: "/live-map", icon: <MapOutlined /> }, { label: "Geofences", to: "/geofences", icon: <LocationOnOutlined /> }, { label: "Devices", to: "/devices", icon: <DevicesOutlined /> }, { label: "Event history", to: "/events", icon: <HistoryOutlined /> }, { label: "Audit logs", to: "/audit-logs", icon: <PolicyOutlined /> }];
function Sidebar() { const location = useLocation(); return <Drawer variant="permanent" sx={{ width, flexShrink: 0, "& .MuiDrawer-paper": { width, boxSizing: "border-box", border: 0, background: "linear-gradient(180deg, #102a43 0%, #0b2035 100%)", color: "#f7fbff" } }}><Toolbar sx={{ px: "24px !important", minHeight: "76px !important" }}><Stack direction="row" alignItems="center" spacing={1.2}><Box sx={{ width: 34, height: 34, display: "grid", placeItems: "center", borderRadius: 2, bgcolor: "primary.main", fontWeight: 800 }}></Box><Box><Typography variant="h6" lineHeight={1.1}>GeoSystem</Typography><Typography variant="caption" sx={{ color: "#9fb3c8" }}></Typography></Box></Stack></Toolbar><Divider sx={{ borderColor: "rgba(159, 179, 200, .2)" }} /><List sx={{ px: 1.5, pt: 2 }}>{menu.map(item => <ListItemButton key={item.to} component={Link} to={item.to} selected={item.to === "/" ? location.pathname === "/" : location.pathname.startsWith(item.to)} sx={{ borderRadius: 2.5, mb: .7, minHeight: 48, "&.Mui-selected": { bgcolor: "#246bfd", boxShadow: "0 8px 18px rgba(36,107,253,.26)" }, "&:hover": { bgcolor: "rgba(255,255,255,.08)" } }}><ListItemIcon sx={{ color: "inherit", minWidth: 42 }}>{item.icon}</ListItemIcon><ListItemText primary={item.label} primaryTypographyProps={{ fontWeight: 600 }} /></ListItemButton>)}</List></Drawer>; }
export default function App() { return <Box sx={{ display: "flex" }}><CssBaseline /><Sidebar /><Box component="main" sx={{ flexGrow: 1, minWidth: 0, bgcolor: "background.default", minHeight: "100vh" }}><AppBar position="static" elevation={0} color="inherit" sx={{ bgcolor: "rgba(255,255,255,.92)", borderBottom: "1px solid #e5edf7" }}><Toolbar sx={{ minHeight: "76px !important" }}><Typography variant="h6" sx={{ flexGrow: 1 }}>Geofencing Location Event Detection</Typography><Stack direction="row" alignItems="center" spacing={1.2} sx={{ pl: 2, borderLeft: "1px solid #e5edf7" }}><Avatar sx={{ bgcolor: "secondary.main", width: 38, height: 38 }}>A</Avatar><Box><Typography variant="body2" fontWeight={750}>Admin</Typography><Typography variant="caption" color="text.secondary">System administrator</Typography></Box></Stack></Toolbar></AppBar><Box sx={{ p: { xs: 2, md: 4 } }}><Routes><Route path="/" element={<DashboardPage />} /><Route path="/live-map" element={<LiveMapPage />} /><Route path="/geofences" element={<GeofencesPage />} /><Route path="/geofences/new" element={<GeofenceFormPage />} /><Route path="/geofences/:id/edit" element={<GeofenceFormPage />} /><Route path="/devices" element={<DevicesPage />} /><Route path="/events" element={<EventsPage />} /><Route path="/audit-logs" element={<AuditLogsPage />} /></Routes></Box></Box></Box>; }
